### ISSUE TITLE
Meta issue: new data types

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#662]
With #554 nearing merge-ability, I'd like to start tracking support for some new datatypes somewhere. That place is here.

### datatypes to be added

- [ ] times #455
  - [ ] numpy date times
  - [ ] pandas date times
- [x] nullable pandas arrays #504

### Potential additions/ possible experimental support

- [x] Ragged arrays via awkard array #647 #609
- [ ] Ranges
- [ ] Time deltas
- [ ] `xarray.DataArrays`
